# Generated by Django 5.0.6 on 2024-05-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestellterArtikel',
            new_name='BestellteArtikel',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='name',
        ),
    ]
